"""Tests for chat-artifact micro-signals (issue #113 / platform #1090)."""

import os
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(ROOT, "skills", "ai-slop-detection", "scripts")
sys.path.insert(0, SCRIPTS)

from chat_artifacts import find_chat_artifacts, CHAT_ARTIFACTS


def ids(text):
    return {f["id"] for f in find_chat_artifacts(text)}


class SchemaTests(unittest.TestCase):
    def test_each_signal_has_keep_when_and_examples(self):
        for pid, meta in CHAT_ARTIFACTS.items():
            self.assertIn("keep_when", meta, f"{pid} missing keep_when guard")
            self.assertIn("example_slop", meta)
            self.assertIn("example_fix", meta)

    def test_detect_only_schema(self):
        for f in find_chat_artifacts("# Phase 2: now we add it\n"):
            self.assertEqual(set(f), {"id", "confidence", "evidence", "keep_when"})

    def test_clean_code_has_no_findings(self):
        text = (
            "def run():\n"
            "    # Retry once on transient errors.\n"
            "    for attempt in range(2):\n"
            "        try:\n"
            "            return fetch()\n"
            "        except Timeout:\n"
            "            continue\n"
        )
        self.assertEqual(find_chat_artifacts(text), [])

    # --- elision-comment ---

    def test_elision_comment_positive(self):
        self.assertIn("elision-comment", ids("// ... rest of the code remains unchanged"))
        self.assertIn("elision-comment", ids("# remaining methods omitted for brevity"))
        self.assertIn("elision-comment", ids("public void run() {\n    // ... rest of the implementation stays the same\n}"))

    def test_elision_comment_negative_no_comment_marker(self):
        # prose elision without a code-comment marker is NOT this signal
        self.assertNotIn("elision-comment", ids("The rest of the code remains unchanged."))
        self.assertNotIn("elision-comment", ids("// falls through to the shared handler"))

    # --- chat-preamble ---

    def test_chat_preamble_positive(self):
        self.assertIn("chat-preamble", ids("Certainly! Here's the updated handler:"))
        self.assertIn("chat-preamble", ids("Of course! Below is the revised file."))
        self.assertIn("chat-preamble", ids("I've made the changes as requested."))

    def test_chat_preamble_negative_not_first_line(self):
        # only the first non-empty line counts
        self.assertNotIn(
            "chat-preamble",
            ids("def a():\n    return 'Certainly! Here is the fix'\n"),
        )
        self.assertNotIn("chat-preamble", ids("def run(): pass"))

    # --- fence-in-code ---

    def test_fence_in_code_positive(self):
        self.assertIn("fence-in-code", ids("def a():\n    pass\n        ```\n"))

    def test_fence_in_code_negative_column0_or_markdown(self):
        # fences at column 0 (markdown/docstring body) are the normal case
        self.assertNotIn("fence-in-code", ids("```python\nprint(1)\n```"))

    # --- meta-process-comment ---

    def test_meta_process_comment_positive(self):
        self.assertIn("meta-process-comment", ids("# Phase 2: now we add the handler"))
        self.assertIn("meta-process-comment", ids("// assistant behavior stays unchanged"))
        self.assertIn("meta-process-comment", ids("# generated by the model as an AI assistant"))

    def test_meta_process_comment_negative_code_content(self):
        self.assertNotIn("meta-process-comment", ids("# Phase 1 of the build: fetch deps"))
        self.assertNotIn("meta-process-comment", ids("# parse the model config file"))

    # --- list-label-marker ---

    def test_list_label_marker_positive(self):
        self.assertIn("list-label-marker", ids("- G1: Introduce the product"))
        self.assertIn("list-label-marker", ids("## NG2. Pricing"))

    def test_list_label_marker_negative_plain_prose(self):
        self.assertNotIn("list-label-marker", ids("- Introduce the product"))
        self.assertNotIn("list-label-marker", ids("Use version G1 of the module."))

    # --- placeholder-credential-shape ---

    def test_placeholder_credential_positive(self):
        self.assertIn("placeholder-credential-shape", ids('API_KEY = "your-api-key"'))
        self.assertIn("placeholder-credential-shape", ids("password: changeme"))
        self.assertIn("placeholder-credential-shape", ids('token = "***"'))
        self.assertIn("placeholder-credential-shape", ids("api_key = <your key here>"))

    def test_placeholder_credential_negative_real_or_prose(self):
        real = "token = sk_live_9f8e7d6c5b4a"  # real credential, not placeholder
        self.assertNotIn("placeholder-credential-shape", ids(real))
        # prose mention is not an assignment
        self.assertNotIn("placeholder-credential-shape", ids("Paste your api key into the settings."))


if __name__ == "__main__":
    unittest.main()
